######################################################################
# Automatically generated by qmake (2.01a) jeu. 1. oct. 16:20:47 2015
######################################################################

TEMPLATE = app
TARGET = 
QT +=network
DEPENDPATH += .
INCLUDEPATH += C:/Users/BEN/Desktop/ServeurActivix/. .

# Input
HEADERS += serveur.h
FORMS += serveur.ui
SOURCES += main.cpp serveur.cpp
